spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: -
            client-secret: -
            scope: profile, email

  datasource:
    url: -
    username: -
    password: -

logging:
  level:
    root: info
    org.springframework.security: TRACE

cors:
  allow:
    origins: http://localhost:3000, https://untitled-a.vercel.app/, https://soundforest.kro.kr/
    methods: GET, POST, PUT, DELETE, PATCH, OPTION

jwt:
  expiration_time: 604800000 #1000*60*60*24*7; 7?
  secret: -

cookie:
  domain: localhost
  max-age: 604800  # 60*60*24*7, 7?

server:
  front: http://localhost:3000
  api: http://localhsot:8080
  error-page: http://localhost:3000
  login-page: http://localhost:3000
